server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

spring.datasource:
    url: jdbc:mysql://127.0.0.1:3306/canal_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 121212
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1

canal:
    adminUser: admin
    adminPasswd: admin
